apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: wanderlust
spec:
  accessModes:
    - ReadWriteOnce
  storageClaimName: ""
  resources:
    requests:
      storage: 5Gi
